name: Commit Message Check

on:
  pull_request_target:

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: conventional-changelog/action@v1
        with:
          preset: eslint