name: Release Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Deps
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Semantic Release
        id: semantic-release
        uses: semantic-release/github@v11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          branches: ['main']
          plugins:
            - "@semantic-release/commit-analyzer"
            - "@semantic-release/release-notes-generator"
            - "@semantic-release/github"
            - "@semantic-release/npm"

      - name: Create GitHub Release
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semantic-release.outputs.new_release_version }}
          release_name: Release ${{ steps.semantic-release.outputs.new_release_version }}
          body: ${{ steps.semantic-release.outputs.release_notes }}
          draft: false
          prerelease: ${{ contains(steps.semantic-release.outputs.new_release_version, '-') }} # Set to true for pre-releases

      - name: Slack Notification (Optional)
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: slackapi/slack-github-action@v1
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: your-slack-channel
          slack-message: |
            New release published: ${{ steps.semantic-release.outputs.new_release_version }}
            ${{ steps.semantic-release.outputs.release_notes }}
            See: ${{ steps.semantic-release.outputs.html_url }}